name: Raise PR on change
on:
  pull_request:
    types: [closed]

jobs:
  raise-pr-on-change:
    if: github.event.pull_request.merged == true
    name: Raise PR on change
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Raise PR on change
        uses: mheap/raise-pr-on-change-action@v1
        with:
          token: ${{ secrets.PAT }}
          configFile: ".github/raise-pr-on-change.json"
          prBranch: automated-update
          targetBranch: main
          prTitle: "Automated update X"
          prBody: "This adds files based on upstream repo Y"
