name: Raise PR on change
on:
  pull_request:
    types: [closed]

jobs:
  raise-pr-on-change:
    name: Raise PR on change
    runs-on: ubuntu-latest
    steps:
      - name: Raise PR on change
        uses: mheap/github-action-readme@v1
        env:
          GITHUB_TOKEN:
        with:
          token: ${{ secrets.PAT }}
          configFile: ".github/raise-pr-on-change.json"
          prBranch: automated-update
          targetBranch: main
          prTitle: "Automated update X"
          prBody: "This adds files based on upstream repo Y"
